[package]
name = "vm"
version = "0.1.0"
authors = ["Srinivas Lade <srinulade1@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
chrono = "0.4"
codespan-reporting = "0.11"
structopt = "0.3"
fxhash = "0.2"
itertools = "0.10"
logos = "0.12"

derives = { path = "../derives" }
