[package]
name = "vm"
version = "0.1.0"
authors = ["Srinivas Lade <srinulade1@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
fxhash = "0.2.1"
itertools = "0.10.1"
logos = "0.12.0"

derives = { path = "../derives" }
